### PR TITLE
updated regex

### PR DESCRIPTION
**Pull request by mrslwiseman**
Hey jackson. 
Even though ive used git quite a bit, this is my first pull request! actually something that I felt I could help with for once yay!

I've tested this, all file names are looking first class.

Not sure why all the line returns come up as a change ? I didnt touch them.

### CODE REVIEW

**Comment by JacksonBates** [comment]
Thanks, Matt. I'll take a proper look this evening.

**Review by JacksonBates — APPROVED** [review]
Good fix, thanks :+1:

I think the noisy diff from the white space edits might be an editor plugin you're using...something like prettier, maybe?

You're PR reminded me I need to delete the index.js file for this branch, since it only relates to the cli version, and that has it's own branch now.

**Comment by JacksonBates** [comment]
fixes #7

**Comment by mrslwiseman** [comment]
cool that was a good feeling contributing. I helped make a thing! yes I
wondered what was going on there with index.js file...

**Comment by mrslwiseman** [comment]
yeah it must be prettify doing that...

**Pull request merged**
